[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.node"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
